In [62]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import matplotlib.pyplot as plt #for graph plotting

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename)) 
#import necessary machine learning library
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/nba-data/Advanced.csv
/kaggle/input/nba-data/Player Season Info.csv
/kaggle/input/nba-data/Player Career Info.csv
/kaggle/input/nba-data/Player Shooting.csv
/kaggle/input/nba-data/Opponent Stats Per Game.csv
/kaggle/input/nba-data/Player Totals.csv
/kaggle/input/nba-data/Opponent Stats Per 100 Poss.csv
/kaggle/input/nba-data/Per 100 Poss.csv
/kaggle/input/nba-data/Team Summaries.csv
/kaggle/input/nba-data/Player Per Game.csv
/kaggle/input/nba-data/All-Star Selections.csv
/kaggle/input/nba-data/End of Season Teams (Voting).csv
/kaggle/input/nba-data/Player Play By Play.csv
/kaggle/input/nba-data/End of Season Teams.csv
/kaggle/input/nba-data/Team Stats Per 100 Poss.csv
/kaggle/input/nba-data/Per 36 Minutes.csv
/kaggle/input/nba-data/Opponent Totals.csv
/kaggle/input/nba-data/Team Abbrev.csv
/kaggle/input/nba-data/Player Award Shares.csv
/kaggle/input/nba-data/Team Totals.csv
/kaggle/input/nba-data/Team Stats Per Game.csv


**3-point evolution in NBA using data from history**

NBA history data from https://www.kaggle.com/code/benbcoleman/2023-nba-all-star-predictions?kernelSessionId=116885548

In [63]:
player_shooting = pd.read_csv("/kaggle/input/nba-data/Player Shooting.csv")
features = ['avg_dist_fga', 'percent_fga_from_x2p_range', 'percent_fga_from_x0_3_range',
       'percent_fga_from_x3_10_range', 'percent_fga_from_x10_16_range',
       'percent_fga_from_x16_3p_range', 'percent_fga_from_x3p_range']
#create target_variable
success_thres = 0.5 # 50% above is considered good percentage shot in NBA
target_variable = 'shot_successful'
player_shooting[target_variable] = (player_shooting['fg_percent'] >= success_thres).astype(int) # return 0 or 1 
df_subset = player_shooting[features + [target_variable]]
ndf = df_subset.dropna()
X = ndf.drop(["shot_successful"], axis = 1)
y = ndf["shot_successful"]

Exploratory Data Analysis (EDA):

Begin with EDA to understand the trends in three-point shooting. Explore the following aspects:
Historical three-point shooting percentages.
The distribution of three-point attempts and makes.
Player and team records related to three-point shooting.
Team strategies in different eras.

In [64]:
# we won't use heaves shot because it is too far and it is for inhuman.
X_train,X_test,y_train,y_test = train_test_split(X, y , test_size = .33, random_state = 42)
model = LogisticRegression()
model.fit(X_train, y_train)

# Make predictions on the test set
y_pred = model.predict(X_test)

# Evaluate the model's performance
accuracy = accuracy_score(y_test, y_pred)
confusion = confusion_matrix(y_test, y_pred)
#classification_report = classification_report(y_test, y_pred)

# Print the evaluation results
print("Accuracy:", accuracy)
print("Confusion Matrix:\n", confusion)
#print("Classification Report:\n", classification_report)

Accuracy: 0.8513162773451983
Confusion Matrix:
 [[4153  211]
 [ 591  439]]


# randomforest classifier : less accurate than logistic regression

In [65]:
from sklearn.ensemble import RandomForestClassifier
# we won't use heaves shot because it is too far and it is for inhuman.
X_train,X_test,y_train,y_test = train_test_split(X, y , test_size = .33, random_state = 42)
nmodel = RandomForestClassifier(n_estimators=100, random_state=42)
nmodel.fit(X_train, y_train)

# Make predictions on the test set
y_pred = nmodel.predict(X_test)

# Evaluate the model's performance
accuracy = accuracy_score(y_test, y_pred)
confusion = confusion_matrix(y_test, y_pred)
#classification_report = classification_report(y_test, y_pred)

# Print the evaluation results
print("Accuracy:", accuracy)
print("Confusion Matrix:\n", confusion)
#print("Classification Report:\n", classification_report)

Accuracy: 0.8455691509084168
Confusion Matrix:
 [[4075  289]
 [ 544  486]]


# Decision Tree model : less accurate than rainforest and logistic regression

In [66]:
from sklearn.tree import DecisionTreeClassifier
# we won't use heaves shot because it is too far and it is for inhuman.
X_train,X_test,y_train,y_test = train_test_split(X, y , test_size = .33, random_state = 42)
xmodel = DecisionTreeClassifier(random_state=42)
xmodel.fit(X_train, y_train)

# Make predictions on the test set
y_pred = xmodel.predict(X_test)

# Evaluate the model's performance
accuracy = accuracy_score(y_test, y_pred)
confusion = confusion_matrix(y_test, y_pred)
#classification_report = classification_report(y_test, y_pred)

# Print the evaluation results
print("Accuracy:", accuracy)
print("Confusion Matrix:\n", confusion)
#print("Classification Report:\n", classification_report)

Accuracy: 0.7842046718576196
Confusion Matrix:
 [[3731  633]
 [ 531  499]]


# SVC has more accuracy than logistic regression

In [67]:
from sklearn.svm import SVC
# we won't use heaves shot because it is too far and it is for inhuman.
X_train,X_test,y_train,y_test = train_test_split(X, y , test_size = .33, random_state = 42)
ymodel = SVC(kernel='linear', random_state=42)

ymodel.fit(X_train, y_train)

# Make predictions on the test set
y_pred = ymodel.predict(X_test)

# Evaluate the model's performance
accuracy = accuracy_score(y_test, y_pred)
confusion = confusion_matrix(y_test, y_pred)
#classification_report = classification_report(y_test, y_pred)

# Print the evaluation results
print("Accuracy:", accuracy)
print("Confusion Matrix:\n", confusion)
#print("Classification Report:\n", classification_report)

Accuracy: 0.8526140155728588
Confusion Matrix:
 [[4171  193]
 [ 602  428]]


# GradientBoostingClassifier has more accuracy than SVC

In [68]:
from sklearn.ensemble import GradientBoostingClassifier
# we won't use heaves shot because it is too far and it is for inhuman.
X_train,X_test,y_train,y_test = train_test_split(X, y , test_size = .33, random_state = 42)
zmodel = GradientBoostingClassifier(n_estimators=100, random_state=42)

zmodel.fit(X_train, y_train)

# Make predictions on the test set
y_pred = zmodel.predict(X_test)

# Evaluate the model's performance
accuracy = accuracy_score(y_test, y_pred)
confusion = confusion_matrix(y_test, y_pred)
#classification_report = classification_report(y_test, y_pred)

# Print the evaluation results
print("Accuracy:", accuracy)
print("Confusion Matrix:\n", confusion)
#print("Classification Report:\n", classification_report)

Accuracy: 0.853726362625139
Confusion Matrix:
 [[4107  257]
 [ 532  498]]


In [69]:
from sklearn.ensemble import GradientBoostingClassifier
# we won't use heaves shot because it is too far and it is for inhuman.
X_train,X_test,y_train,y_test = train_test_split(X, y , test_size = .33, random_state = 42)
zmodel = GradientBoostingClassifier(n_estimators=100, random_state=42)

zmodel.fit(X_train, y_train)

# Make predictions on the test set
y_pred = zmodel.predict(X_test)

# Evaluate the model's performance
accuracy = accuracy_score(y_test, y_pred)
confusion = confusion_matrix(y_test, y_pred)
#classification_report = classification_report(y_test, y_pred)

# Print the evaluation results
print("Accuracy:", accuracy)
print("Confusion Matrix:\n", confusion)
#print("Classification Report:\n", classification_report)

Accuracy: 0.853726362625139
Confusion Matrix:
 [[4107  257]
 [ 532  498]]


> So I founded the most accurate method for this project is GradientBoostingClassifier which has 85.3726362625139 accuracy. The model that we made can optimize shot selection, which can improve by getting more data such as the real coordinates of shooting, shot-clock left, defender's attribute, and etc. This project can improve to implement in real world for coach or nba players for more efficiency in their shooting. :)